"""empty message

Revision ID: 29f3ac20b9aa
Revises: 91da71e7dfc3
Create Date: 2023-06-12 16:40:45.926618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f3ac20b9aa'
down_revision = '91da71e7dfc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hornor_title', sa.String(length=100), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clicks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('clicks')

    with op.batch_alter_table('honor', schema=None) as batch_op:
        batch_op.drop_column('hornor_title')

    # ### end Alembic commands ###
