"""empty message

Revision ID: 91da71e7dfc3
Revises: 262d22975b13
Create Date: 2023-06-07 16:29:36.575212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91da71e7dfc3'
down_revision = '262d22975b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_categories', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('news_categories')

    # ### end Alembic commands ###
