"""初始化数据库

Revision ID: ace5db57ce1a
Revises: 
Create Date: 2025-01-08 17:18:07.592300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace5db57ce1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('banner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banner_timestamp'), ['timestamp'], unique=False)

    op.create_table('brand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_timestamp'), ['timestamp'], unique=False)

    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_timestamp'), ['timestamp'], unique=False)

    op.create_table('contactcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('honor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('honor_title', sa.String(length=100), nullable=True),
    sa.Column('honor_img', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('honor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_honor_timestamp'), ['timestamp'], unique=False)

    op.create_table('introducecategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('introducecategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_introducecategory_timestamp'), ['timestamp'], unique=False)

    op.create_table('newscategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('newscategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newscategory_timestamp'), ['timestamp'], unique=False)

    op.create_table('researchcategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('researchcategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_researchcategory_timestamp'), ['timestamp'], unique=False)

    op.create_table('subject',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_timestamp'), ['timestamp'], unique=False)

    op.create_table('contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('contact_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_category_id'], ['contactcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('introduce',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('introduce_content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('introduce_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['introduce_category_id'], ['introducecategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('introduce', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_introduce_timestamp'), ['timestamp'], unique=False)

    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('newscategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['newscategory_id'], ['newscategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_timestamp'), ['timestamp'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('product_indication', sa.String(length=200), nullable=True),
    sa.Column('product_content', sa.Text(), nullable=True),
    sa.Column('product_format', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_timestamp'), ['timestamp'], unique=False)

    op.create_table('research',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('research_content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('research_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_category_id'], ['researchcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_timestamp'), ['timestamp'], unique=False)

    op.create_table('photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('filename_s', sa.String(length=256), nullable=True),
    sa.Column('filename_m', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('filename_m'),
    sa.UniqueConstraint('filename_s')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_timestamp'))

    op.drop_table('research')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_timestamp'))

    op.drop_table('product')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_timestamp'))

    op.drop_table('news')
    with op.batch_alter_table('introduce', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_introduce_timestamp'))

    op.drop_table('introduce')
    op.drop_table('contact')
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_timestamp'))

    op.drop_table('subject')
    with op.batch_alter_table('researchcategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_researchcategory_timestamp'))

    op.drop_table('researchcategory')
    with op.batch_alter_table('newscategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newscategory_timestamp'))

    op.drop_table('newscategory')
    with op.batch_alter_table('introducecategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_introducecategory_timestamp'))

    op.drop_table('introducecategory')
    with op.batch_alter_table('honor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_honor_timestamp'))

    op.drop_table('honor')
    op.drop_table('contactcategory')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_timestamp'))

    op.drop_table('category')
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_timestamp'))

    op.drop_table('brand')
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banner_timestamp'))

    op.drop_table('banner')
    op.drop_table('admin')
    # ### end Alembic commands ###
