"""add resarch tables

Revision ID: e67b0be23681
Revises: 
Create Date: 2024-12-06 16:48:23.385800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67b0be23681'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researchcategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('researchcategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_researchcategory_timestamp'), ['timestamp'], unique=False)

    op.create_table('research',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('research_content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('research_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_category_id'], ['researchcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_timestamp'))

    op.drop_table('research')
    with op.batch_alter_table('researchcategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_researchcategory_timestamp'))

    op.drop_table('researchcategory')
    # ### end Alembic commands ###
